### ISSUE TITLE
error in compilation using cmake (version 2.8.11.2)

### ISSUE THREAD

**Issue by Punzo** [healpy/cfitsio#1]
I am trying to compile with cmake (version 2.8.11.2) on linux system. I get the error reported below.

If I download the current version of cfitsio (3.370) from http://heasarc.gsfc.nasa.gov/fitsio/fitsio.html  
the error is fixed and the compilation go smoothly. 

May you update this git repository with the last version (3.370). I'd like to use Cfitisio in a git/cmake project and this will help a lot. 

Thanks in advance,

Best Regards,

Davide.

Report:

Linking C shared library liblibcfitsio.so
[ 92%] Built target libcfitsio
Scanning dependencies of target FPack
[ 93%] Building C object CMakeFiles/FPack.dir/fpack.c.o
[ 95%] Building C object CMakeFiles/FPack.dir/fpackutil.c.o
/home/davide/Downloads/cfitsio-master/fpackutil.c: In function ‘fp_info_hdu’:
/home/davide/Downloads/cfitsio-master/fpackutil.c:340:17: warning: format ‘%lu’ expects a matching ‘long unsigned int’ argument [-Wformat=]
                 sprintf (msg, " SUMS=%lu/%lu", (unsigned long) (~((int) hdusum), datasum)); fp_msg (msg);
                 ^
/home/davide/Downloads/cfitsio-master/fpackutil.c: In function ‘fp_test’:
/home/davide/Downloads/cfitsio-master/fpackutil.c:1332:4: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 5 has type ‘LONGLONG’ [-Wformat=]
    printf("\n File: %s, HDU %d,  %d cols X %ld rows\n", infits, extnum, ncols, nrows);
    ^
Linking C executable FPack
CMakeFiles/FPack.dir/fpackutil.c.o: In function `fp_test':
fpackutil.c:(.text+0x37e0): undefined reference to `log10'
liblibcfitsio.so.CFITSIO_VERSION: undefined reference to `sinh'
liblibcfitsio.so.CFITSIO_VERSION: undefined reference to `ceil'
liblibcfitsio.so.CFITSIO_VERSION: undefined reference to `atan2'
liblibcfitsio.so.CFITSIO_VERSION: undefined reference to `tanh'
liblibcfitsio.so.CFITSIO_VERSION: undefined reference to `cosh'
liblibcfitsio.so.CFITSIO_VERSION: undefined reference to `acos'
liblibcfitsio.so.CFITSIO_VERSION: undefined reference to `sin'
liblibcfitsio.so.CFITSIO_VERSION: undefined reference to `atan'
liblibcfitsio.so.CFITSIO_VERSION: undefined reference to `asin'
liblibcfitsio.so.CFITSIO_VERSION: undefined reference to `exp'
liblibcfitsio.so.CFITSIO_VERSION: undefined reference to `tan'
liblibcfitsio.so.CFITSIO_VERSION: undefined reference to `cos'
liblibcfitsio.so.CFITSIO_VERSION: undefined reference to `log'
liblibcfitsio.so.CFITSIO_VERSION: undefined reference to `pow'
liblibcfitsio.so.CFITSIO_VERSION: undefined reference to `sqrt'
liblibcfitsio.so.CFITSIO_VERSION: undefined reference to `floor'
collect2: error: ld returned 1 exit status
CMakeFiles/FPack.dir/build.make:114: recipe for target 'FPack' failed
make[2]: *** [FPack] Error 1
CMakeFiles/Makefile2:63: recipe for target 'CMakeFiles/FPack.dir/all' failed
make[1]: *** [CMakeFiles/FPack.dir/all] Error 2
Makefile:85: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zonca** [comment]
could you make a pull request for that?
I'd be happy to merge, thanks

**Comment by Punzo** [comment]
Thanks for the merging. This is fixed.
